/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.Container;
import tp6.DirectorioTelefonico;

/**
 *
 * @author OzKuro
 */
public class JFramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form DirectorioTelefonico
     */
    private final Container framePrincipal;
    private JPanelAgregarCliente jPAgregarCliente;
    private JPanelBuscarCliente jPBuscarCliente;
    private JPanelBorrarCliente jPBorrarCliente;
    private final DirectorioTelefonico dirTel;

    public DirectorioTelefonico getDirTel() {
        return dirTel;
    }
    
    public JFramePrincipal() {
        initComponents();
        this.setTitle("Directorio telefonico - Facundo Venturi");
        this.framePrincipal = getContentPane();
        this.dirTel = new DirectorioTelefonico();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jLabelBy = new javax.swing.JLabel();
        btnBorrarCliente = new javax.swing.JButton();
        btnBuscarCliente = new javax.swing.JButton();
        btnAgregarClientes = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Directorio Telefonico");
        setForeground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(500, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jPanelMain.setBackground(java.awt.Color.darkGray);
        jPanelMain.setForeground(java.awt.Color.black);

        jLabelBy.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelBy.setForeground(java.awt.Color.white);
        jLabelBy.setText("Realizado por Facundo Venturi");

        btnBorrarCliente.setBackground(java.awt.Color.gray);
        btnBorrarCliente.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnBorrarCliente.setForeground(java.awt.Color.black);
        btnBorrarCliente.setText(" Borrar cliente");
        btnBorrarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBorrarCliente.setMaximumSize(new java.awt.Dimension(250, 25));
        btnBorrarCliente.setMinimumSize(new java.awt.Dimension(250, 25));
        btnBorrarCliente.setPreferredSize(new java.awt.Dimension(250, 25));
        btnBorrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarClienteActionPerformed(evt);
            }
        });

        btnBuscarCliente.setBackground(java.awt.Color.gray);
        btnBuscarCliente.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnBuscarCliente.setForeground(java.awt.Color.black);
        btnBuscarCliente.setText("Buscar cliente");
        btnBuscarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarCliente.setMaximumSize(new java.awt.Dimension(250, 25));
        btnBuscarCliente.setMinimumSize(new java.awt.Dimension(250, 25));
        btnBuscarCliente.setPreferredSize(new java.awt.Dimension(250, 25));
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        btnAgregarClientes.setBackground(java.awt.Color.gray);
        btnAgregarClientes.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnAgregarClientes.setForeground(java.awt.Color.black);
        btnAgregarClientes.setText("Agregar cliente");
        btnAgregarClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarClientes.setMaximumSize(new java.awt.Dimension(250, 25));
        btnAgregarClientes.setMinimumSize(new java.awt.Dimension(250, 25));
        btnAgregarClientes.setPreferredSize(new java.awt.Dimension(250, 25));
        btnAgregarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClientesActionPerformed(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabelTitulo.setForeground(java.awt.Color.black);
        jLabelTitulo.setText("Directorio Telefonico");

        btnSalir.setBackground(java.awt.Color.darkGray);
        btnSalir.setForeground(java.awt.Color.white);
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                        .addComponent(btnSalir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelBy, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                        .addGap(0, 33, Short.MAX_VALUE)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAgregarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBorrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                                .addComponent(jLabelTitulo)
                                .addGap(81, 81, 81))))))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelTitulo)
                .addGap(29, 29, 29)
                .addComponent(btnAgregarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnBorrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 239, Short.MAX_VALUE)
                .addComponent(jLabelBy, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarClienteActionPerformed
        jPBorrarCliente = new JPanelBorrarCliente(this);
        this.setContentPane(jPBorrarCliente);
        this.invalidate();
        this.validate();
    }//GEN-LAST:event_btnBorrarClienteActionPerformed

    private void btnAgregarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClientesActionPerformed
        //internalAgregarClientes iac = new internalAgregarClientes();
        //getContentPane()
        //jPanelMain.removeAll();
        //jPanelMain.add(iac);
        //jPanelMain.repaint();
        //jPanelMain.revalidate();
        //iac.setVisible(true);
        jPAgregarCliente = new JPanelAgregarCliente(this);
        this.setContentPane(jPAgregarCliente);
        this.invalidate();
        this.validate();
    }//GEN-LAST:event_btnAgregarClientesActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        jPBuscarCliente = new JPanelBuscarCliente(this);
        this.setContentPane(jPBuscarCliente);
        this.invalidate();
        this.validate();
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    public void volverAlMenu() {
        this.setContentPane(framePrincipal);
        this.invalidate();
        this.validate();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarClientes;
    private javax.swing.JButton btnBorrarCliente;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabelBy;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelMain;
    // End of variables declaration//GEN-END:variables
}
